//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PayRoll.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Branch_tbl
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Branch_tbl()
        {
            this.Employee_tbl = new HashSet<Employee_tbl>();
        }
    
        public int id { get; set; }
        public string Branch_Code { get; set; }
        public string Branch_Name { get; set; }
        public Nullable<short> Status { get; set; }
        public Nullable<int> User_Id { get; set; }
        public Nullable<int> Create_by { get; set; }
        public Nullable<System.DateTime> Create_Date { get; set; }
        public Nullable<int> Update_by { get; set; }
        public Nullable<System.DateTime> Update_Date { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Employee_tbl> Employee_tbl { get; set; }
    }
}
