//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PayRoll.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Employee_tbl
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Employee_tbl()
        {
            this.Employee_Attendance_tbl = new HashSet<Employee_Attendance_tbl>();
            this.Issue_Salary_Subtbl = new HashSet<Issue_Salary_Subtbl>();
            this.SalarySetup_tbl = new HashSet<SalarySetup_tbl>();
        }
    
        public int id { get; set; }
        public string Employee_Code { get; set; }
        public string First_Name { get; set; }
        public string Last_Name { get; set; }
        public string Gender { get; set; }
        public Nullable<System.DateTime> DOB { get; set; }
        public Nullable<System.DateTime> DOJ { get; set; }
        public string Email { get; set; }
        public string Mobile { get; set; }
        public Nullable<int> Designation { get; set; }
        public Nullable<int> Branch { get; set; }
        public string Present_Address1 { get; set; }
        public string Present_Address2 { get; set; }
        public string Present_City { get; set; }
        public string Present_State { get; set; }
        public string Present_Pincode { get; set; }
        public string Permanent_Address1 { get; set; }
        public string Permanent_Address2 { get; set; }
        public string Permanent_City { get; set; }
        public string Permanent_State { get; set; }
        public string Permanent_Pincode { get; set; }
        public string Bank_Name { get; set; }
        public string Account_No { get; set; }
        public string IFSC_Code { get; set; }
        public string Branch_Name { get; set; }
        public Nullable<short> Status { get; set; }
        public Nullable<int> User_Id { get; set; }
        public Nullable<int> Create_by { get; set; }
        public Nullable<System.DateTime> Create_Date { get; set; }
        public Nullable<int> Update_by { get; set; }
        public Nullable<System.DateTime> Update_Date { get; set; }
        public string ProfileImage { get; set; }
    
        public virtual Branch_tbl Branch_tbl { get; set; }
        public virtual Designation_tbl Designation_tbl { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Employee_Attendance_tbl> Employee_Attendance_tbl { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Issue_Salary_Subtbl> Issue_Salary_Subtbl { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<SalarySetup_tbl> SalarySetup_tbl { get; set; }
    }
}
