//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PayRoll.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Issue_Salary_Subtbl
    {
        public int id { get; set; }
        public Nullable<int> Issue_Salary_Id { get; set; }
        public Nullable<int> Employee { get; set; }
        public Nullable<decimal> Loss_of_pay { get; set; }
        public Nullable<decimal> Advance_amt { get; set; }
        public Nullable<decimal> Net_Salary { get; set; }
        public Nullable<int> Salary_Status { get; set; }
    
        public virtual Employee_tbl Employee_tbl { get; set; }
        public virtual Issue_Salary_tbl Issue_Salary_tbl { get; set; }
    }
}
