//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PayRoll.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Issue_Salary_tbl
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Issue_Salary_tbl()
        {
            this.Issue_Salary_Subtbl = new HashSet<Issue_Salary_Subtbl>();
        }
    
        public int id { get; set; }
        public string Month { get; set; }
        public string Year { get; set; }
        public Nullable<int> User_Id { get; set; }
        public Nullable<int> Create_by { get; set; }
        public Nullable<System.DateTime> Create_Date { get; set; }
        public Nullable<int> Update_by { get; set; }
        public Nullable<System.DateTime> Update_Date { get; set; }
        public Nullable<System.DateTime> Salary_Date { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Issue_Salary_Subtbl> Issue_Salary_Subtbl { get; set; }
    }
}
