//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PayRoll.Models
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class PayRoll_Entities : DbContext
    {
        public PayRoll_Entities()
            : base("name=PayRoll_Entities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<Branch_tbl> Branch_tbl { get; set; }
        public virtual DbSet<Designation_tbl> Designation_tbl { get; set; }
        public virtual DbSet<Employee_Attendance_tbl> Employee_Attendance_tbl { get; set; }
        public virtual DbSet<Employee_tbl> Employee_tbl { get; set; }
        public virtual DbSet<Issue_Salary_Subtbl> Issue_Salary_Subtbl { get; set; }
        public virtual DbSet<Issue_Salary_tbl> Issue_Salary_tbl { get; set; }
        public virtual DbSet<SalaryDeduction_tbl> SalaryDeduction_tbl { get; set; }
        public virtual DbSet<SalaryHead_tbl> SalaryHead_tbl { get; set; }
        public virtual DbSet<SalarySetup_Addition_tbl> SalarySetup_Addition_tbl { get; set; }
        public virtual DbSet<SalarySetup_Deduction_tbl> SalarySetup_Deduction_tbl { get; set; }
        public virtual DbSet<SalarySetup_tbl> SalarySetup_tbl { get; set; }
    }
}
