//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PayRoll.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class SalarySetup_Addition_tbl
    {
        public int id { get; set; }
        public Nullable<int> SalarySetup { get; set; }
        public Nullable<int> SalaryHead { get; set; }
        public Nullable<decimal> SalaryHead_Amount { get; set; }
    
        public virtual SalaryHead_tbl SalaryHead_tbl { get; set; }
        public virtual SalarySetup_tbl SalarySetup_tbl { get; set; }
    }
}
