//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PayRoll.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class SalarySetup_tbl
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public SalarySetup_tbl()
        {
            this.SalarySetup_Addition_tbl = new HashSet<SalarySetup_Addition_tbl>();
            this.SalarySetup_Deduction_tbl = new HashSet<SalarySetup_Deduction_tbl>();
        }
    
        public int id { get; set; }
        public Nullable<int> Employee { get; set; }
        public Nullable<decimal> CTC_Amount { get; set; }
        public Nullable<decimal> Net_Pay { get; set; }
        public Nullable<int> User_Id { get; set; }
        public Nullable<int> Create_by { get; set; }
        public Nullable<System.DateTime> Create_Date { get; set; }
        public Nullable<int> Update_by { get; set; }
        public Nullable<System.DateTime> Update_Date { get; set; }
        public Nullable<decimal> Total_Deduction { get; set; }
    
        public virtual Employee_tbl Employee_tbl { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<SalarySetup_Addition_tbl> SalarySetup_Addition_tbl { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<SalarySetup_Deduction_tbl> SalarySetup_Deduction_tbl { get; set; }
    }
}
